#!/usr/bin/env bun
// Per-folder index.md generator. New (issue #1) — no Python original.
//   scripts/index.ts               regenerate index.md in every configured dir with >=1 note
//   scripts/index.ts <dir> [dir…]  regenerate index.md only for the named dir(s)
// Generated index.md files carry NO frontmatter (validator skips basename index.md) and start
// with the "generated by scripts/index.ts" header below — regenerate, don't hand-edit them.
import { readFileSync, writeFileSync, readdirSync, existsSync } from "node:fs";
import { resolve, join, relative, basename } from "node:path";
import { parseFrontmatter, extractField, extractTagsList, splitLines } from "./frontmatter.ts";
import { loadFromScript, resolveInside } from "./config.ts";

export interface NoteMeta {
  file: string; // filename incl. .md, e.g. "my-note.md"
  title: string; // H1 text, or filename (no ext) fallback
  description: string; // frontmatter 'description', blank if absent
  tags: string[]; // frontmatter tags, [] if absent
  type: string; // frontmatter 'type', blank if absent
  updated: string; // frontmatter 'updated', blank if absent
}

const GENERATED_HEADER = "<!-- generated by scripts/index.ts — regenerate, don't hand-edit -->";

/** First H1 ("# ...") line in a set of lines, trimmed. null if none. Deliberately does not
 *  match "## " (heading level 2+) — the regex requires whitespace immediately after the '#'. */
function extractH1(lines: string[]): string | null {
  for (const line of lines) {
    const m = /^#\s+(.+)$/.exec(line.trim());
    if (m) return m[1].trim();
  }
  return null;
}

/** Extract NoteMeta from a note file. Tolerant of missing/malformed frontmatter — never throws;
 *  falls back to filename-as-title and blank fields (e.g. raw clippings dropped into a vault dir). */
export function loadNoteMeta(path: string): NoteMeta {
  const file = basename(path);
  const fallbackTitle = file.replace(/\.md$/, "");
  let lines: string[];
  try {
    lines = splitLines(readFileSync(path, "utf8"));
  } catch {
    return { file, title: fallbackTitle, description: "", tags: [], type: "", updated: "" };
  }

  const parsed = parseFrontmatter(lines);
  if (!parsed) {
    return { file, title: extractH1(lines) ?? fallbackTitle, description: "", tags: [], type: "", updated: "" };
  }
  return {
    file,
    title: extractH1(parsed.body) ?? fallbackTitle,
    description: extractField(parsed.fm, "description") ?? "",
    tags: extractTagsList(parsed.fm) ?? [],
    type: extractField(parsed.fm, "type") ?? "",
    updated: extractField(parsed.fm, "updated") ?? "",
  };
}

/** All non-index .md notes directly inside `dir`, sorted by filename for deterministic input order. */
export function notesInDir(dir: string): NoteMeta[] {
  return readdirSync(dir)
    .filter((f) => f.endsWith(".md") && f !== "index.md")
    .sort()
    .map((f) => loadNoteMeta(join(dir, f)));
}

function noteLine(n: NoteMeta): string {
  const base = n.file.replace(/\.md$/, "");
  const link = n.title && n.title !== base ? `[[${base}|${n.title}]]` : `[[${base}]]`;
  const meta: string[] = [];
  if (n.type) meta.push(`type: ${n.type}`);
  if (n.tags.length) meta.push(`tags: ${n.tags.join(", ")}`);
  if (n.updated) meta.push(`updated: ${n.updated}`);
  let line = `- ${link}`;
  if (n.description) line += ` — ${n.description}`;
  if (meta.length) line += ` (${meta.join(" · ")})`;
  return line;
}

/** Build full index.md markdown for one vault dir. Pure — same input always yields byte-identical
 *  output (no timestamps, no randomness, no filesystem-order dependence — callers sort notes/groups).
 *  "default": group by type (groups + header sorted alphabetically), reverse-chron by updated within
 *  a group. "alphabetical": flat list sorted by title (how crm/ presents people). */
export function buildIndex(dirName: string, notes: NoteMeta[], style: "default" | "alphabetical"): string {
  const header = `${GENERATED_HEADER}\n\n# ${dirName}\n`;
  if (notes.length === 0) return header + "\n_(no notes yet)_\n";

  if (style === "alphabetical") {
    const sorted = [...notes].sort((a, b) => a.title.localeCompare(b.title));
    return header + "\n" + sorted.map(noteLine).join("\n") + "\n";
  }

  const groups = new Map<string, NoteMeta[]>();
  for (const n of notes) {
    const key = n.type || "untyped";
    if (!groups.has(key)) groups.set(key, []);
    groups.get(key)!.push(n);
  }
  const sections = [...groups.keys()].sort().map((type) => {
    const items = groups.get(type)!
      .slice()
      .sort((a, b) => (b.updated || "").localeCompare(a.updated || "") || a.title.localeCompare(b.title));
    return `\n## ${type}\n\n` + items.map(noteLine).join("\n") + "\n";
  });
  return header + sections.join("");
}

function targetDirs(d: ReturnType<typeof loadFromScript>): string[] {
  return [...Object.values(d.SEMANTIC_DIRS), ...Object.values(d.EPISODIC_DIRS), ...d.cfg.extra_dirs];
}

/** resolve()+startsWith guard — same pattern as safeJoin() in src/init.ts / assertInsideVault()
 *  in src/config.ts. Rejects a CLI dir arg that escapes the vault root via '..' etc. */
function main() {
  const vaultRoot = resolve(import.meta.dir, "..");
  const d = loadFromScript(import.meta.dir);
  const configuredDirs = new Set(targetDirs(d));
  // `index_style` lands on VaultConfig via a concurrently-landing change; cast until merged.
  const styleMap: Record<string, string> = (d.cfg as { index_style?: Record<string, string> }).index_style ?? {};

  const args = process.argv.slice(2);
  let relDirs: string[];
  if (args.length > 0) {
    relDirs = [];
    for (const a of args) {
      let full: string;
      try {
        full = resolveInside(vaultRoot, a);
      } catch (e: any) {
        console.error(`error: ${e.message}`);
        process.exit(2);
      }
      const rel = relative(vaultRoot, full);
      if (configuredDirs.has(rel)) relDirs.push(rel);
    }
  } else {
    relDirs = [...configuredDirs]
      .filter((rel) => existsSync(join(vaultRoot, rel)) && notesInDir(join(vaultRoot, rel)).length > 0)
      .sort();
  }

  let count = 0;
  for (const rel of relDirs) {
    const full = join(vaultRoot, rel);
    if (!existsSync(full)) continue;
    const style = styleMap[rel] === "alphabetical" ? "alphabetical" : "default";
    writeFileSync(join(full, "index.md"), buildIndex(rel, notesInDir(full), style), "utf8");
    console.log(`✓ index.md → ${rel}/`);
    count++;
  }
  if (count === 0) console.log("no target directories with notes found");
}

if (import.meta.main) main();
